---
apiVersion: v1
kind: Secret
metadata:
  name: recombee-credentials
  namespace: "default"
  labels:
    app: "my-app"
type: Opaque
data:
  RECOMBEE_DATABASE_ID: eWFsbGFub3ctZGV2
  RECOMBEE_REGION: Q0FfRUFTVA==
  RECOMBEE_SECRET_TOKEN: dFhPanVlTFdYd3Zjem5xR05NREJWNWExbWI5c0ZLNzlPZ2t5eXRoQlJDWjF5a0xVZFF4ZmZPeHdEN2hOcnByTg==
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "analytics"
  namespace: "default"
  labels:
    app: "analytics"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "analytics"
  template:
    metadata:
      labels:
        app: "analytics"
    spec:
      containers:
      - name: "analytics-sha256-1"
        image: "us-central1-docker.pkg.dev/yallanow-413400/yallanow-services/analytics-service:latest"
        env:
          - name: RECOMBEE_DATABASE_ID
            valueFrom:
              secretKeyRef:
                name: recombee-credentials
                key: RECOMBEE_DATABASE_ID
          - name: RECOMBEE_REGION
            valueFrom:
              secretKeyRef:
                name: recombee-credentials
                key: RECOMBEE_REGION
          - name: RECOMBEE_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: recombee-credentials
                key: RECOMBEE_SECRET_TOKEN
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/google-credentials.json
          - name: AUTH_URL
            value: "http://auth:5001/auth"
        volumeMounts:
          - name: google-credentials
            mountPath: /var/secrets/google
            readOnly: true
      volumes:
        - name: google-credentials
          secret:
            secretName: google-credentials
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "analytics-hpa-oqd9"
  namespace: "default"
  labels:
    app: "analytics"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "analytics"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
