version: '3.8'

services:
  events-service:
    build:
      context: ./events-service
      dockerfile: Dockerfile
    image: events-service:latest
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=[Xi|~'r_SKE6E/qx
      - GOOGLE_APPLICATION_CREDENTIALS=/app/resources/yallanow-413400-32268eb74b33.json
    volumes:
      - ./secret:/app/resources


  groups-service:
    build:
      context: ./groups-service
      dockerfile: Dockerfile
    image: groups-service:latest
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=[Xi|~'r_SKE6E/qx
      - GOOGLE_APPLICATION_CREDENTIALS=/app/resources/yallanow-413400-32268eb74b33.json
    volumes:
      - ./secret:/app/resources

  images-service:
    build:
      context: ./images-service
      dockerfile: Dockerfile
    image: images-service:latest
    ports:
      - "8083:8080"
    environment:
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=[Xi|~'r_SKE6E/qx
      - GOOGLE_APPLICATION_CREDENTIALS=/app/resources/yallanow-413400-32268eb74b33.json
      - CLOUDINARY_URL=cloudinary://533577523476422:kfeLf7-oZ1ZVWu0D3Gfj0LX3gzU@dt8r2amry
    volumes:
      - ./secret:/app/resources

  feed-service:
    build:
      context: ./feed-service
      dockerfile: Dockerfile
    image: feed-service:latest
    ports:
      - "8084:8080"
    environment:
      - RECOMBEE_DATABASE_ID=yallanow-dev
      - RECOMBEE_REGION=CA_EAST
      - RECOMBEE_SECRET_TOKEN=tXOjueLWXwvcznqGNMDBV5a1mb9sFK79OgkyythBRCZ1ykLUdQxffOxwD7hNrprN=

  analytics-service:
    build:
      context: ./analytics-service
      dockerfile: Dockerfile
    image: analytics-service:latest
    ports:
      - "8085:8080"
    environment:
      - RECOMBEE_DATABASE_ID=yallanow-dev
      - RECOMBEE_REGION=CA_EAST
      - RECOMBEE_SECRET_TOKEN=tXOjueLWXwvcznqGNMDBV5a1mb9sFK79OgkyythBRCZ1ykLUdQxffOxwD7hNrprN=
      - GOOGLE_APPLICATION_CREDENTIALS=/app/resources/yallanow-413400-32268eb74b33.json
    volumes:
      - ./secret:/app/resources

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: auth-service:latest
    ports:
      - "5001:5001"